supported_tags:
  - 悲傷
  - 舒緩
  - 空靈
  - 舞曲
  - 愉悅甜蜜
  - 古風
  - 台灣華語
  - 2000 年代流行曲
  - OST 主題曲
  - 改編音樂
  - 開車精選
  - 測試精選
  - 純音樂
supported_languages:
  chi: 中文
  eng: 英語
  kor: 韓語
  zhx: 台語
  jpn: 日語
  fra: 法語
allow_folders:
  - "A 純音樂"
  - "B 人聲"
  - "C 民歌"